define(["routes/router",
    "routes/ApplicationRoute",
    "routes/AuthenticatedRoute",
    "routes/IndexRoute",
    "routes/user/UserLoginRoute",
    "routes/claim/ClaimRoute",
    "routes/claim/ClaimEditRoute",
    "routes/claim/ClaimAddevidenceRoute",
    "routes/crises/CrisesCreateRoute",
    "routes/crises/CrisesIndexRoute",
    "routes/crisis/CrisisRoute",
    "routes/crisis/CrisisMakeclaimRoute",
    "routes/crisis/CrisisIndexRoute",
    "routes/crisis/CrisisEditRoute",
    "routes/evidence/EvidenceRoute",
    "routes/evidence/EvidenceIndexRoute",
    "routes/evidence/EvidenceEditRoute",
    "routes/share/ResolveshareRoute",
    "controllers/ApplicationController",
    "controllers/IndexController",
    "controllers/user/UserLoginController",
    "controllers/claim/ClaimController",
    "controllers/claim/ClaimIndexController",
    "controllers/claim/ClaimEditController",
    "controllers/claim/ClaimAddevidenceController",
    "controllers/crises/CrisesController",
    "controllers/crises/CrisesCreateController",
    "controllers/crises/CrisesIndexController",
    "controllers/crisis/CrisisController",
    "controllers/crisis/CrisisMakeclaimController",
    "controllers/crisis/CrisisIndexController",
    "controllers/crisis/CrisisEditController",
    "controllers/evidence/EvidenceController",
    "controllers/evidence/EvidenceIndexController",
    "controllers/evidence/EvidenceEditController",
    "views/CitiesAutoCompleteFieldView",
    "views/TagsAutoCompleteFieldView",
    "views/MapInfoView",
    "views/MapMarkerCreateView",
    "views/MapPolygonCreateView",
    "views/UserLoginView",
    "views/CrisesCreateView",
    "views/CrisisEditView",
    "views/CrisisSeverityView",
    "views/ClaimEditView",
    "views/EvidenceEditView",
    "views/ClaimAddevidenceView",
    "views/CrisisMakeclaimView",
    "views/EvidenceIndexView",
    "views/RichHTMLView",
    "views/ImageUploaderView",
    "views/CrisesMapView",
    "views/CoverImageView",
    "views/ShareView",
    "models/Crisis",
    "models/Claim",
    "models/Evidence",
    "models/Tag",
    "models/User",
    "models/Comment",
    "models/Errors",
    "models/Error",
    'tinyPubSub',
    'dropzone'
],
        function(
                Router,
                ApplicationRoute,
                AuthenticatedRoute,
                IndexRoute,
                UserLoginRoute,
                ClaimRoute,
                ClaimEditRoute,
                ClaimAddevidenceRoute,
                CrisesCreateRoute,
                CrisesIndexRoute,
                CrisisRoute,
                CrisisMakeclaimRoute,
                CrisisIndexRoute,
                CrisisEditRoute,
                EvidenceRoute,
                EvidenceIndexRoute,
                EvidenceEditRoute,
                ResolveshareRoute,
                ApplicationController,
                IndexController,
                UserLoginController,
                ClaimController,
                ClaimIndexController,
                ClaimEditController,
                ClaimAddevidenceController,
                CrisesController,
                CrisesCreateController,
                CrisesIndexController,
                CrisisController,
                CrisisMakeclaimController,
                CrisisIndexController,
                CrisisEditController,
                EvidenceController,
                EvidenceIndexController,
                EvidenceEditController,
                CitiesAutoCompleteFieldView,
                TagsAutoCompleteFieldView,
                MapInfoView,
                MapMarkerCreateView,
                MapPolygonCreateView,
                UserLoginView,
                CrisesCreateView,
                CrisisEditView,
                CrisisSeverityView,
                ClaimEditView,
                EvidenceEditView,
                ClaimAddevidenceView,
                CrisisMakeclaimView,
                EvidenceIndexView,
                RichHTMLView,
                ImageUploaderView,
                CrisesMapView,
                CoverImageView,
                ShareView,
                Crisis,
                Claim,
                Evidence,
                Tag,
                User,
                Comment,
                Errors,
                Error

                ) {

            "use strict";
            /*Module Pattern*/
            var App = {
                LOG_TRANSITIONS: true,
                LOG_ACTIVE_GENERATION: true,
                LOG_VIEW_LOOKUPS: true,
                LOG_STACKTRACE_ON_DEPRECATION: true,
                LOG_BINDINGS: true,
                LOG_TRANSITIONS_INTERNAL: false,
                prevPath: '',
                Router: Router,
                // Load routes
                ApplicationRoute: ApplicationRoute,
                AuthenticatedRoute: AuthenticatedRoute,
                IndexRoute: IndexRoute,
                UserLoginRoute: UserLoginRoute,
                ClaimRoute: ClaimRoute,
                ClaimEditRoute: ClaimEditRoute,
                ClaimAddevidenceRoute: ClaimAddevidenceRoute,
                CrisesCreateRoute: CrisesCreateRoute,
                CrisesIndexRoute: CrisesIndexRoute,
                CrisisRoute: CrisisRoute,
                CrisisMakeclaimRoute: CrisisMakeclaimRoute,
                CrisisIndexRoute: CrisisIndexRoute,
                CrisisEditRoute: CrisisEditRoute,
                EvidenceRoute: EvidenceRoute,
                EvidenceIndexRoute: EvidenceIndexRoute,
                EvidenceEditRoute: EvidenceEditRoute,
                ResolveshareRoute: ResolveshareRoute,
                //Load Controllers
                ApplicationController: ApplicationController,
                IndexController: IndexController,
                UserLoginController: UserLoginController,
                ClaimController: ClaimController,
                ClaimIndexController: ClaimIndexController,
                ClaimEditController: ClaimEditController,
                ClaimAddevidenceController: ClaimAddevidenceController,
                CrisesController: CrisesController,
                CrisesCreateController: CrisesCreateController,
                CrisesIndexController: CrisesIndexController,
                CrisisController: CrisisController,
                CrisisMakeclaimController: CrisisMakeclaimController,
                CrisisIndexController: CrisisIndexController,
                CrisisEditController: CrisisEditController,
                EvidenceController: EvidenceController,
                EvidenceIndexController: EvidenceIndexController,
                EvidenceEditController: EvidenceEditController,
                //Load Views
                CitiesAutoCompleteFieldView: CitiesAutoCompleteFieldView,
                TagsAutoCompleteFieldView: TagsAutoCompleteFieldView,
                MapInfoView: MapInfoView,
                MapMarkerCreateView: MapMarkerCreateView,
                MapPolygonCreateView: MapPolygonCreateView,
                UserLoginView: UserLoginView,
                CrisesCreateView: CrisesCreateView,
                CrisisEditView: CrisisEditView,
                CrisisSeverityView: CrisisSeverityView,
                ClaimEditView: ClaimEditView,
                EvidenceEditView: EvidenceEditView,
                ClaimAddevidenceView: ClaimAddevidenceView,
                CrisisMakeclaimView: CrisisMakeclaimView,
                EvidenceIndexView: EvidenceIndexView,
                RichHTMLView: RichHTMLView,
                ImageUploaderView: ImageUploaderView,
                CrisesMapView: CrisesMapView,
                CoverImageView: CoverImageView,
                ShareView:ShareView,
                //Load Models
                Crisis: Crisis,
                Claim: Claim,
                Evidence: Evidence,
                Tag: Tag,
                User: User,
                Comment: Comment,
                Errors: Errors,
                Error: Error,
                //init for application path
                currentPath: ''
            };

            return App;
        });
